/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

// This service connects our app to the database
// Like a bridge between our code and the data storage

import { Injectable } from '@nestjs/common'; // Injectable makes this a service, Logger for printing messages
import { ConfigService } from '@nestjs/config'; // Service to read configuration settings
import { PrismaClient } from './../generated/prisma/client'; // Database client generated by Prisma
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'; // SQLite database adapter

@Injectable() // This decorator tells NestJS this is a service that can be injected
export class PrismaService extends PrismaClient {
  // We extend PrismaClient to add our own features
  constructor(private readonly configService: ConfigService) {
    // ConfigService is injected automatically
    // Get the database URL from our configuration (.env file)
    const databaseUrl = configService.getOrThrow<string>('DATABASE_URL');

    // Create the database adapter with our URL
    const adapter = new PrismaBetterSqlite3({ url: databaseUrl });

    // Call the parent constructor with our adapter
    super({ adapter });
  }
}
